## Project

### 1. Read Module

In [1]:
import dash
from dash import html, dcc
from dash.dependencies import Input, Output
import plotly.graph_objects as go
from dash import dash_table as dt
from dash import State

from datetime import datetime
import pandas as pd
import numpy as np

### 2. Read CSV File

In [2]:
df_company_info = pd.read_csv('data/df_krx.csv', index_col=0)
# 6자리 숫자 맞춰주기, 앞에 0을 붙여주기 위해 map을 사용
df_company_info['Symbol'] = df_company_info['Symbol'].map('{:06}'.format) 

df_stock_price = pd.read_csv('data/df_stock_price.csv', index_col=0)
df_stock_price.index = pd.to_datetime(df_stock_price.index)
df_stock_price

,3S,AJ네트웍스,AK홀딩스,APS홀딩스,AP시스템,AP위성,BGF,BGF리테일,BNGT,BNK금융지주,...,휴온스,휴온스글로벌,휴젤,흥구석유,흥국,흥국에프엔비,흥국화재,흥아해운,희림,힘스
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,2190,4530,51900,4205,21500,6600,7960,205500,6290,7000,...,51237,35972,126448,2675,6860,1301,4795,4760,4590,4799
2019-01-03,2180,4535,50000,4200,21600,6550,7860,209500,6030,6880,...,48525,34238,122697,2585,6690,1291,4775,4783,4605,4824
2019-01-04,2240,4535,49300,4050,21100,6540,7840,214000,6150,6880,...,50409,34758,119184,2650,8300,1279,4840,4666,4575,4819
2019-01-07,2260,4520,50600,4115,22200,6550,7720,207500,6300,6850,...,51615,34671,119218,2660,7730,1269,4995,4842,4555,4889
2019-01-08,2250,4505,50200,3995,22050,6350,7650,205500,6440,6740,...,50936,34629,115945,2645,7830,1313,5070,4807,4585,4894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-02,2780,7280,15900,13250,18950,10900,3990,156000,4075,6560,...,34350,20950,117000,6290,6450,2865,3295,1660,9980,6880
2022-09-05,2755,7240,15500,12850,18950,10500,3935,154500,4075,6600,...,34150,20750,116300,7090,6300,2805,3295,1580,10300,6680
2022-09-06,2790,7410,15800,13300,19000,10650,3970,155500,4075,6560,...,34350,20800,116600,7400,6460,2815,3350,1600,10700,6870
2022-09-07,2760,7710,15550,13400,18350,10300,3900,157500,4075,6440,...,33500,20100,113100,6880,6210,2750,3325,1565,10250,6800
2022-09-08,2840,7990,15750,13550,18850,10300,3935,158500,4075,6510,...,33250,20050,114300,6610,6210,2745,3350,1605,9960,7060

In [3]:
display(df_company_info.head())
display(df_stock_price.head())

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,"박대현, 손삼달",http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도

,3S,AJ네트웍스,AK홀딩스,APS홀딩스,AP시스템,AP위성,BGF,BGF리테일,BNGT,BNK금융지주,...,휴온스,휴온스글로벌,휴젤,흥구석유,흥국,흥국에프엔비,흥국화재,흥아해운,희림,힘스
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,2190,4530,51900,4205,21500,6600,7960,205500,6290,7000,...,51237,35972,126448,2675,6860,1301,4795,4760,4590,4799
2019-01-03,2180,4535,50000,4200,21600,6550,7860,209500,6030,6880,...,48525,34238,122697,2585,6690,1291,4775,4783,4605,4824
2019-01-04,2240,4535,49300,4050,21100,6540,7840,214000,6150,6880,...,50409,34758,119184,2650,8300,1279,4840,4666,4575,4819
2019-01-07,2260,4520,50600,4115,22200,6550,7720,207500,6300,6850,...,51615,34671,119218,2660,7730,1269,4995,4842,4555,4889
2019-01-08,2250,4505,50200,3995,22050,6350,7650,205500,6440,6740,...,50936,34629,115945,2645,7830,1313,5070,4807,4585,4894

In [8]:
app = dash.Dash()

app.layout = html.Div([

     # Div1
     html.Div(id='Div1',
                 children=[
                     html.H1('Standard Stock Price Graph',
                             style={'textAlign': 'center'}),

                     html.Br(),

                     dcc.Dropdown(id='Div1 Dropdown',
                                  multi=True,
                                  style={'width': '60%',
                                         'fontSize' : 12},
                                  ),
                    # Div1 Date
                    html.Div(id='Div1 Date',
                             children=[
                                 html.H4('Input Start Date & End Date'),
                                 
                                 dcc.Input(id='start_date', 
                                           value='2020-01-01', 
                                           style={'fontSize': 12}),
                                 
                                 dcc.Input(id='end_date', 
                                           value='2021-01-01', 
                                           style={'fontSize': 12}),
                                 
                                 html.Button(id='Div1 Button', 
                                             n_clicks=0, 
                                             children='Submit',
                                             style={'fontSize': 12}),
                                 
                                 ]),
                    # Div1 Graph
                    html.Div(id='Div1 Graph',
                             children = [
                                 dcc.Graph(id='Div1_stock_graph'),
                      ]),
               # Div1 Finish
               ], style={'color': 'green', 'border': 'green solid'}),

     # Div2
     html.Div(id='Div2',
                 children=[
                      # Div2 Layout
                    html.H1('Find Sector',
                              style={'textAlign': 'center'}),
                      
                    html.Br(),
                      
                    html.H4('Input Stock'),
                      
                    dcc.Input(id='Div2 Input', 
                              value='삼성전자', 
                              style={'fontSize': 12}),
                    html.Button(id='Div2 Button', 
                                n_clicks=0, 
                                children='Submit'),
                                ]),

                    html.Br(),

                    # Div2 Sector
                    html.Div(id='Div2 Result',
                             children=['None'],
                             style={'fontSize': 12}),  
                             
                    html.Br(),

                    # Div2 Table                                              
                    html.Div(id='Div2 Table',
                                 children=['None'],
                              ),
               # Div2 Finish
               ], style={'color': 'blue', 'border': 'blue solid'})                 


@app.callback([Output('Div2 Result', 'children'),
               Output('Div2 Table', 'children'),
               Output('Div1 Dropdown', 'options')],
              [Input('Div2 Button', 'n_clicks')],
              [State('Div2 Input', 'value')])
def search_stock_sector(n_clicks, stock_name):
    
    # Div2 Result
    sector = df_company_info[df_company_info['Name'] == stock_name]['Sector'].values[0]

    # Div2 Table
    df_samle = df_company_info[df_company_info['Sector'] == sector][['Symbol', 'Name', 'Industry']]
    data = df_samle.to_dict('records')
    columns = [{'name': i, 'id': i} for i in df_samle.columns]
    tab_res = dt.DataTable(data=data, columns=columns, style_cell={'textAlign': 'center'})

    # Div1 Dropdown
    dropdown_index = df_company_info[df_company_info['Sector'] == sector]['Name']
    drop_res = [{'label': i, 'value': i} for i in dropdown_index]

    return sector, tab_res, drop_res

@app.callback(Output('Div1_stock_graph', 'figure'),
              Input('Div1 Button', 'n_clicks'),
              State('Div1 Dropdown', 'value'),
              State('start_date', 'value'),
              State('end_date', 'value'))
def standard_stock_price_graph(n_clicks, stock_name, start_date, end_date):
    start = datetime.strptime(start_date, '%Y-%m-%d')
    end = datetime.strptime(end_date, '%Y-%m-%d')

    df_sample = df_stock_price.loc[start:end, stock_name]
    
    data = []

    for col in df_sample:
        trace = go.Scatter(x=df_sample[col].index,
                           y=df_sample[col]/df_sample[col][0],
                           mode='lines',
                           name='{}'.format(col))
        data.append(trace)

    layout = go.Layout(title='Stock Standard Price Graph',
                       yaxis={'tickformat':','})
    fig = go.Figure(data=data, layout=layout)
    fig.update_layout(template='none')

    return fig


if __name__ == '__main__':
     app.run_server(debug=True)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\hslio\anaconda3\envs\lhs_3.10\lib\site-packages\pandas\core\indexes\base.py:3790, in Index.get_loc(
    self=Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템...
       '힘스'],
      dtype='object', length=2524),
    key=None
)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
        casted_key = None
        self = Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템', 'AP위성', 'BGF', 'BGF리테일',
       'BNGT', 'BNK금융지주',
       ...
       '휴온스', '휴온스글로벌', '휴젤', '흥구석유', '흥국', '흥국에프엔비', '흥국화재', '흥아해운', '희림',
       '힘스'],
      dtype='object', length=2524)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
KeyError: None

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\hslio\anaconda3\envs\lhs_3.10\lib\site-packages\pandas\core\indexes\base.py:3790, in Index.get_loc(
    self=Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템...
       '힘스'],
      dtype='object', length=2524),
    key=None
)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
        casted_key = None
        self = Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템', 'AP위성', 'BGF', 'BGF리테일',
       'BNGT', 'BNK금융지주',
       ...
       '휴온스', '휴온스글로벌', '휴젤', '흥구석유', '흥국', '흥국에프엔비', '흥국화재', '흥아해운', '희림',
       '힘스'],
      dtype='object', length=2524)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
KeyError: None

C:\Users\hslio\AppData\Local\Temp\ipykernel_4956\1416192506.py:118: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\hslio\AppData\Local\Temp\ipykernel_4956\1416192506.py:118: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\hslio\AppData\Local\Temp\ipykernel_4956\1416192506.py:118: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\hslio\AppData\Local\Temp\ipykernel_4956\1416192506.py:118: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

In [5]:
stock_name = "삼성전자"

sector = df_company_info[df_company_info['Name'] == stock_name]['Sector'].values[0]
df_sample = df_company_info[df_company_info['Sector'] == sector][['Symbol', 'Name', 'Industry']]
df_sample.to_dict('records')

[{'Symbol': '211270', 'Name': 'AP위성', 'Industry': '위성통신 단말기'},
 {'Symbol': '065770',
  'Name': 'CS',
  'Industry': '이동통신중계기, 위성방송(DMB)중계기(Gap-Filler)'},
 {'Symbol': '066570',
  'Name': 'LG전자',
  'Industry': '이동통신단말기,C-TV,V.C.R.,컴퓨터,완전평면 TV,플라즈마 디스플레이 패널 TV,전자제품(세탁기외),CDMA(코드분할다중접속)이동통신,전자교환기,전송기기'},
 {'Symbol': '218410', 'Name': 'RFHIC', 'Industry': 'GaN 트랜지스터'},
 {'Symbol': '192410', 'Name': 'THQ', 'Industry': '기지국 안테나, 인바운드플랫폼'},
 {'Symbol': '078890', 'Name': '가온미디어', 'Industry': '디지털셋톱박스'},
 {'Symbol': '029480',
  'Name': '광무',
  'Industry': '네트워크 통합사업,네트워크 장비, 光 전송장비, S/W 제조, 네트워크관리'},
 {'Symbol': '035460',
  'Name': '기산텔레콤',
  'Industry': '광모듈, 에코 켄슬러, 중계기, VoIP Server등'},
 {'Symbol': '340360', 'Name': '다보링크', 'Industry': 'AP, APController 외'},
 {'Symbol': '039560', 'Name': '다산네트웍스', 'Industry': '네트워크 통신장비'},
 {'Symbol': '008110', 'Name': '대동전자', 'Industry': '통신음향,전자기계기구용 플라스틱제품 제조,도매'},
 {'Symbol': '000300', 'Name': '대유플러스', 'Industry': '유,무선 통신장비'},
 {'Symbol': '069540', 'Name': '라이트론', 'Industry': '기타무선통신장비제조업'},
 {'Symbol': '100590',
  'Name': '머큐리',
  'Industry': 'AP 단말기, 광섬유 및 광케이블, 위성통신 전송장비'},
 {'Symbol': '101330', 'Name': '모베이스', 'Industry': '휴대전화 케이스'},
 {'Symbol': '046310', 'Name': '백금T&A', 'Industry': '레이더디텍터'},
 {'Symbol': '121800', 'Name': '비덴트', 'Industry': '방송용 LCD모니터'},
 {'Symbol': '005930',
  'Name': '삼성전자',
  'Industry': 'IMT2000 서비스용 동기식 기지국,교환국장비,데이터단말기,동영상휴대폰,핵심칩,반도체제품,사무,계산 및 회계용기계'},
 {'Symbol': '065570', 'Name': '삼영이엔씨', 'Industry': 'GMDSS장비, GPS플로터 등'},
 {'Symbol': '037460', 'Name': '삼지전자', 'Industry': '통신기기,정보기기,BACKLIGHTUNIT사업'},
 {'Symbol': '032750', 'Name': '삼진', 'Industry': '리모컨'},
 {'Symbol': '093920', 'Name': '서원인텍', 'Industry': '휴대폰용키패드및부자재'},
 {'Symbol': '178320', 'Name': '서진시스템', 'Industry': '통신장비부품,휴대폰부품(메탈케이스 등)'},
 {'Symbol': '081580',
  'Name': '성우전자',
  'Industry': '휴대폰금속프레스부품(전자파차단ShieldCan)'},
 {'Symbol': '236200', 'Name': '슈프리마', 'Industry': '바이오인식 관련 제품'},
 {'Symbol': '094840', 'Name': '슈프리마에이치큐', 'Industry': '지문인식솔루션및시스템'},
 {'Symbol': '033790', 'Name': '스카이문스테크놀로지', 'Industry': '무선통신시스템용 중계기'},
 {'Symbol': '036710', 'Name': '심텍홀딩스', 'Industry': '반도체용 인쇄회로기판'},
 {'Symbol': '050890', 'Name': '쏠리드', 'Industry': '이동통신중계기,위성DMB용중계기'},
 {'Symbol': '245450', 'Name': '씨앤에스링크', 'Industry': '내비게이션, LTE Router, 블랙박스'},
 {'Symbol': '058220', 'Name': '아리온', 'Industry': '디지털셋톱박스'},
 {'Symbol': '143160',
  'Name': '아이디스',
  'Industry': '영상보안장치(DVR,NVR,IP-Camera 등)'},
 {'Symbol': '297570', 'Name': '알로이스', 'Industry': '안드로이드 OTT 멀티미디어 디바이스'},
 {'Symbol': '061040', 'Name': '알에프텍', 'Industry': '핸드폰 충전기, 핸즈프리'},
 {'Symbol': '096630', 'Name': '에스코넥', 'Industry': 'WaferProber'},
 {'Symbol': '088800', 'Name': '에이스테크', 'Industry': '단말기용안테나,기지국용안테나'},
 {'Symbol': '224110', 'Name': '에이텍티앤', 'Industry': '교통카드단말기'},
 {'Symbol': '230240', 'Name': '에치에프알', 'Industry': '유선 및 무선통신장비 제조 및 제조서비스'},
 {'Symbol': '073540', 'Name': '에프알텍', 'Industry': '이동통신용중계기'},
 {'Symbol': '138080', 'Name': '오이솔루션', 'Industry': '광트랜시버'},
 {'Symbol': '109080', 'Name': '옵티시스', 'Industry': '광링크 모듈 등'},
 {'Symbol': '115440', 'Name': '우리넷', 'Industry': '광전송장비(MSPP), 교환장비(AGW)'},
 {'Symbol': '140660', 'Name': '위월드', 'Industry': '이동위성통신안테나, 위성방송시스템'},
 {'Symbol': '203450', 'Name': '유니온커뮤니티', 'Industry': '지문인식출입통제기'},
 {'Symbol': '264450', 'Name': '유비쿼스', 'Industry': '스위치, FTTH'},
 {'Symbol': '073490', 'Name': '이노와이어리스', 'Industry': '통신용 시험 및 계측장비'},
 {'Symbol': '215790', 'Name': '이노인스트루먼트', 'Industry': '기업 인수 합병'},
 {'Symbol': '083640', 'Name': '인콘', 'Industry': '영상보안장비 및 영상보안솔루션'},
 {'Symbol': '049070',
  'Name': '인탑스',
  'Industry': '휴대용단말기 부품, 가전 부품, 자동차 부품, 의료기기 제품, 로봇 관련 제품 제조 등'},
 {'Symbol': '189300',
  'Name': '인텔리안테크',
  'Industry': '위성통신 안테나, 해상용 위성방송 수신안테나'},
 {'Symbol': '175140', 'Name': '인포마크', 'Industry': '웨어러블 디바이스, 모바일 라우터'},
 {'Symbol': '174880', 'Name': '장원테크', 'Industry': '스마트폰 및 태블릿PC Bracket'},
 {'Symbol': '361390', 'Name': '제노코', 'Industry': '위성탑재체, 위성운용국, 항공전자 등'},
 {'Symbol': '109070', 'Name': '컨버즈', 'Industry': 'ICS중계기, 블랙박스'},
 {'Symbol': '079190', 'Name': '케스피온', 'Industry': '휴대폰안테나'},
 {'Symbol': '032500', 'Name': '케이엠더블유', 'Industry': 'RF 부품 및 중계기'},
 {'Symbol': '036690', 'Name': '코맥스', 'Industry': '홈네트워크시스템,CCTV 방송설비'},
 {'Symbol': '189350', 'Name': '코셋', 'Industry': '광통신용 증폭기'},
 {'Symbol': '056360',
  'Name': '코위버',
  'Industry': '가입가계 가입자계 광단국장치,SONs-51,OMS-155M,OCSU,E2 가입자 전송장비,SDS-2500 등'},
 {'Symbol': '015710', 'Name': '코콤', 'Industry': '비디오도어폰'},
 {'Symbol': '134580', 'Name': '탑코미디어', 'Industry': '셋톱박스'},
 {'Symbol': '091440', 'Name': '텔레필드', 'Industry': '광전송장비'},
 {'Symbol': '200230',
  'Name': '텔콘RF제약',
  'Industry': 'RF 통신부품(케이블 어셈블리, 커넥터 등)'},
 {'Symbol': '084730', 'Name': '팅크웨어', 'Industry': '내비게이션,블랙박스,태블릿 및 위치정보서비스'},
 {'Symbol': '170790',
  'Name': '파이오링크',
  'Industry': 'ADC(서버부하 분산장치), 보안스위치, 웹방화벽'},
 {'Symbol': '038950',
  'Name': '파인디지털',
  'Industry': '원격 RF 감시장치, 디지털 광 중계기, 노드분배기'},
 {'Symbol': '106240', 'Name': '파인테크닉스', 'Industry': '휴대폰부품, 소형LCD부품, LED조명기기'},
 {'Symbol': '062970',
  'Name': '피피아이',
  'Industry': '데이터센터용 AWG, 통신용 AWG, 스플리터, 계측기 등'},
 {'Symbol': '039010', 'Name': '현대에이치티', 'Industry': '스마트홈 제조'},
 {'Symbol': '005870', 'Name': '휴니드', 'Industry': '무선통신기기,군납용무전기,위성방송수신기 제조'}]

In [6]:
start_date = '2020-01-01'
end_date = '2020-05-01'

start = datetime.strptime(start_date, '%Y-%m-%d')
end = datetime.strptime(end_date, '%Y-%m-%d')

df_stock_price.loc[start : end, ['삼성전자', 'SK하이닉스']]

             삼성전자  SK하이닉스
Date
2020-01-02  55200   94700
2020-01-03  55500   94500
2020-01-06  55500   94300
2020-01-07  55800   94000
2020-01-08  56800   97400
...           ...     ...
2020-04-23  49850   82600
2020-04-24  49350   81400
2020-04-27  49850   82600
2020-04-28  50100   83400
2020-04-29  50000   83700

[82 rows x 2 columns]

In [7]:
for col in df_sample:
    trace = go.Scatter(x=df_sample[col].index,
                       y=df_sample[col]/df_sample[col][0],
                       mode='lines',
                       name='{}'.format(col))
    data.append(trace)

layout = go.Layout(title='Stock Standard Price Graph',
                   yaxis={'tickformat':','})
fig = go.Figure(data=data, layout=layout)
fig.show()

KeyError: 0

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\hslio\anaconda3\envs\lhs_3.10\lib\site-packages\pandas\core\indexes\base.py:3790, in Index.get_loc(
    self=Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템...
       '힘스'],
      dtype='object', length=2524),
    key=None
)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
        casted_key = None
        self = Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템', 'AP위성', 'BGF', 'BGF리테일',
       'BNGT', 'BNK금융지주',
       ...
       '휴온스', '휴온스글로벌', '휴젤', '흥구석유', '흥국', '흥국에프엔비', '흥국화재', '흥아해운', '희림',
       '힘스'],
      dtype='object', length=2524)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
KeyError: None

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\hslio\anaconda3\envs\lhs_3.10\lib\site-packages\pandas\core\indexes\base.py:3790, in Index.get_loc(
    self=Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템...
       '힘스'],
      dtype='object', length=2524),
    key=None
)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
        casted_key = None
        self = Index(['3S', 'AJ네트웍스', 'AK홀딩스', 'APS홀딩스', 'AP시스템', 'AP위성', 'BGF', 'BGF리테일',
       'BNGT', 'BNK금융지주',
       ...
       '휴온스', '휴온스글로벌', '휴젤', '흥구석유', '흥국', '흥국에프엔비', '흥국화재', '흥아해운', '희림',
       '힘스'],
      dtype='object', length=2524)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
KeyError: None

C:\Users\hslio\AppData\Local\Temp\ipykernel_4956\3143836182.py:118: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
NameError: name 'data' is not defined